name: 00 - Hola Actions

on:
  workflow_dispatch:

permissions: {}

jobs:
  saludo:
    name: Saludo
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir un mensaje
        run: echo "Hola desde GitHub Actions"
